export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'

export const FILTER_BY_MULTI_RANGE = 'FILTER_BY_MULTI_RANGE'
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY'
export const FILTER_BY_BRAND = 'FILTER_BY_BRAND'
export const FILTER_BY_RATING = 'FILTER_BY_RATING'    
export const FILTER_BY_STOCK = 'FILTER_BY_IN_STOCK'
export const FILTER_BY_SEARCH = 'FILTER_BY_SEARCH'
export const SORT_BY_PRICE = 'SORT_BY_PRICE'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
